### ISSUE TITLE
Problem with CtrlPort?

### ISSUE THREAD

**Issue by dcmcshan** [lofaldli/gr-ccsds#7]
I have noticed that CCSDS Decoder block does not play well with CtrlPort (using for performance monitoring).  Any idea why?  If I turn ControlPort on in conf file,  It (sometimes) exits with return code -11 (sometimes it just exits)

**Comment by lofaldli** [comment]
I don't remember having run into any issues like this.
If you could provide some more details or steps to reproduce, I can try to be a bit more helpful.
