### ISSUE TITLE
RS interleave sequence not correct ?

### ISSUE THREAD

**Issue by catbraincell** [lofaldli/gr-ccsds#8]
https://deepspace.jpl.nasa.gov/dsndocs/810-005/208/208B.pdf
see page 24, rs decode output should "re-interleaved" to restore original order.

**Comment by lofaldli** [comment]
i'm not sure i understand what you mean, isn't this what is done in `decode_frame` (line 165)?

https://github.com/lofaldli/gr-ccsds/blob/e13cab4177ae4fef521a1347f04e46b53249a35c/lib/ccsds_decoder_impl.cc#L159-L182

**Comment by catbraincell** [comment]
input sequence, interleave = 8
00 01 02 03 04 05 ff 07 
08 09 0a 0b 0c 0d 0e 0f
10 11 12 13 14 15 16 17 
18 19 1a 1b 1c 1d 1e 1f
......(total 223 * 8)
......(parity 32 * 8)
corrected
00 01 02 03 04 05 06 07 
08 09 0a 0b 0c 0d 0e 0f
......
rs decoder input
decoder 0 - 00 08 10 18 ......
decoder 6 - ff 0e 16 1e ......
....
